CFLAGS="-mtune=haswell -O2 -pipe"
CXXFLAGS="$CFLAGS"
CPPFLAGS="-DNDEBUG"
LDFLAGS="-Wl,-O2"
MAKEFLAGS="-j$(nproc)"
NINJA_STATUS="[%r %f/%t %es] "

unset NINJAJOBS
export CFLAGS CXXFLAGS CPPFLAGS LDFLAGS MAKEFLAGS NINJA_STATUS
